# Generated by Django 2.2.16 on 2022-08-24 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='api_foodgram.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='amount',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='api_foodgram.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
