# Generated by Django 2.2.16 on 2022-08-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_foodgram', '0002_auto_20220817_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='shopping_cart',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='favorites',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=10, verbose_name='Избранный'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='recipes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritess', to='api_foodgram.Recipes'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritess', to=settings.AUTH_USER_MODEL),
        ),
    ]
