# Generated by Django 2.2.16 on 2022-08-23 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_foodgram', '0003_auto_20220822_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribed',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='subscribed',
            name='subscribed',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subscribed', to=settings.AUTH_USER_MODEL, verbose_name='Подписывающийся'),
        ),
        migrations.AlterField(
            model_name='subscribed',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_subscribed', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
