# Generated by Django 2.2.16 on 2022-08-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_foodgram', '0004_auto_20220823_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='favorites',
        ),
    ]
